version: '3.4'

services:

    core:
        depends_on:
            - database
        build:
            context: ./
            dockerfile: ./Dockerfile
        environment:
            - DISCORD_TOKEN=${DISCORD_TOKEN}
            - DB.HOST=database
            - DB=${DB_NAME}
            - DB.USER=${DB_USER}
            - DB.PASSWORD=${DB_PASS}
        links:
            - database
        volumes:
            - ./config/core/:/app/config

    database:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASS}
        volumes:
            - db_vol:/var/lib/mysql
            - ./config/database:/etc/mysql/conf.d

volumes:
    db_vol: